[[redirects]]
  from = "/docs/*"
  to = "https://mxroutedocs.com"
  status = 301
  force = true

[[redirects]]
  from = "/support/*"
  to = "https://accounts.mxroute.com/index.php?/tickets/"
  status = 301
  force = true
